version: '3.5'
services:
  openvino:
    container_name: openvino
    hostname: openvino
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: openvino
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 189:* rmw'
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
